{{- $fullName := include "pvc-exporter.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-pod-pvc-mapping
  namespace: {{.Values.namespace}}
  labels:
    app: {{ $fullName }}
    com: {{ $fullName }}-pod-pvc-mapping
spec:
  replicas: {{ .Values.PodPvcMapping.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ $fullName }}
      com: {{ $fullName }}-pod-pvc-mapping
  template:
    metadata:
      labels:
        app: {{ $fullName }}
        com: {{ $fullName }}-pod-pvc-mapping
    spec:
      imagePullSecrets:
        {{- toYaml .Values.PodPvcMapping.image.pullSecrets | nindent 8 }}
      {{- with .Values.PodPvcMapping.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.PodPvcMapping.tolerations }}
      tolerations:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: pod-pvc-mapping
        {{- with .Values.PodPvcMapping.image }}
        image: "{{ .repository }}{{ if .digest }}@{{ .digest }}{{ else }}:{{ .tag }}{{ end }}"
        imagePullPolicy: {{ .pullPolicy }}
        {{- end }}
        ports:
        - containerPort: {{.Values.PodPvcMapping.containerPort}}
          name: metrics
          protocol: TCP
        livenessProbe:
          {{- toYaml .Values.PodPvcMapping.livenessProbe | nindent 10 }}
      serviceAccountName: {{ $fullName }}-sa